### ISSUE TITLE
Container runs fine, however...

### ISSUE THREAD

**Issue by lucodealethea** [ingomueller-net/docker-hana-express#1]
The HXE instance is running fine via Eclipse Hana Studio, with functionality such as Developement Perspective and Design Time Artefacts, Security in Hana Admin Console, SQL console in Hana Modeler...

However, any Hana XS Classic url like <hostname>:8090/sap/hana/xs/admin/  doesn't further than login form 
http://0.0.0.0:8090/sap/hana/xs/formLogin/login.html?x-sap-origin-location=%2Fsap%2Fhana%2Fxs%2Fadmin%2F

Any idea or suggestion is welcome...

**Comment by ingomueller-net** [comment]
Hey! I have never used this functionality. Can you point me to a guide or some documentation on how to use it? Did you by any chance try this out outside of docker? I am not sure whether this problem is docker related...

**Comment by lucodealethea** [comment]
Well, inside the container, there isn’t any chrome or Firefox installed...but maybe with Hana 2.0 sps2, classic hana XS urls have been decommissioned...I tried to do same install as the docker container, and couldn’t get all XS classic urls to work...I enjoyed the container since it gives all the basics to play with database without the full xsa stack...

**Comment by ingomueller-net** [comment]
I suppose you mean something like described [here](https://blogs.sap.com/2017/08/13/sap-hana-2.0-express-edition-urls-permissions-and-configuration-for-the-xs-classic-server/), right? For this, you wouldn't need a browser in the container, I guess, only on the host.

BTW, did you try opening http://hxehost-src:8090/sap/hana/xs/admin/ in a browser on your host?

**Comment by lucodealethea** [comment]
Will try asap, and give you a feedback. Thx Ingo

**Comment by ingomueller-net** [comment]
I managed to try this out and it works. When you run the final image, run it with `-P` or `-p 8090`, then connect to http://localhost:8090/sap/hana/xs/admin/.
