### ISSUE TITLE
Error when installing HXE

### ISSUE THREAD

**Issue by uxkjaer** [ingomueller-net/docker-hana-express#2]
Hi Ingo, 

I've tried to use your docker installation project, but fail to get it installed. 

I get stuck in the installation process under step:
Installing package 'DAT Configfiles (EN, DE)'...
          Starting external program update-rc.d
Installation of SAP HANA Express Edition System failed.
  Installation of SAP HANA Database failed
    Installation failed
      error installing
        Cannot create system
          Error checking sapinit
            Starting external program update-rc.d
              Command line is: update-rc.d -n sapinit defaults
            Cannot execute program update-rc.d: update-rc.d: No such command

By the way i had to correct the makefile to ingomuellernet/hana-express when i pulled your image from the docker store.

I hope for your help.

**Comment by vencooin** [comment]
I have the same issue. @kovboyjder Did you find a solution for this?

**Comment by ingomueller-net** [comment]
This must be due to a newer version of HANA express. I have recently updated the docker image, which should now work with the latest version of HANA express, and documented which versions are supported. Feel free to re-open the issue if the problem persists for you.

**Comment by sharadvermatitian** [comment]
U need to try to change the /usr/bin/update-rc.d file, as Ubuntu structure has changed and to option -n has been removed now.

add the line - if (/^-n$/) { next }

where u need to add the line is depend upon the version of Ubuntu. like in 18.04 add this line on 321st line in /usr/bin/update-rc.d

Try below:
$ sudo cp /usr/sbin/update-rc.d /usr/sbin/update-rc.d.orig
$ sudo sed -i "321i if (/^-n$/) { next }" /usr/sbin/update-rc.d

**Comment by ingomueller-net** [comment]
@sharadvermatitian I don't understand. The image isn't based on Ubuntu and doesn't use update-rc...

**Comment by sharadvermatitian** [comment]
@ingomueller-net : Sorry for the confusion. i got the same error during my SAP HANA express installation on Ubuntu. So i assumed the OS image is Ubuntu. As mentioned by @kovboyjder the error is (below)
Command line is: update-rc.d -n sapinit defaults
Cannot execute program update-rc.d: update-rc.d: No such command

so i used the above mentioned steps and get it resolved. @kovboyjder you can use the same and give it a try. 

So i tried to help here. Again apologies if any confusions, i have created.

**Comment by ingomueller-net** [comment]
OK, thanks for the clarification and the hint. (BTW, I have chosen OpenSUSE as base image in the hope of gettung similar results as on SLES, which is certified for HANA.)

**Comment by janrrrr** [comment]
Addition for 20.2 LTS since SAP wasnt able to fix it: the line to be added is now in another line: 339 (just insert it right after the other "if (/^-...." statements).
